apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-order-aggregator-service-deployment
  labels:
    app: user-order-aggregator-service
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-order-aggregator-service
      tier: backend
  template:
    metadata:
      labels:
        app: user-order-aggregator-service
        tier: backend
    spec:
      containers:
      - name: user-order-aggregator-service
        image: sc5896/user-order-aggregator-service:latest
        env:
        - name: USER_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              key: USER_SERVICE_URL
              name: service-url-configmap
        - name: ORDER_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              key: ORDER_SERVICE_URL
              name: service-url-configmap
        - name: JAEGER_AGENT_HOST
          value: jaeger-agent
        ports:
        - name: usr-ordr-port
          containerPort: 8080
        imagePullPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
    name: user-order-aggregator-service
spec:
    selector:
        app: user-order-aggregator-service
        tier: backend
    type: LoadBalancer
    ports:
      - protocol: TCP
        port: 8082
        targetPort: usr-ordr-port