apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
  labels:
    app: user-service
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
      tier: backend
  template:
    metadata:
      labels:
        app: user-service
        tier: backend
    spec: 
      containers:
      - name: user
        image: sc5896/user-service:latest
        env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: mysql-configmap
                key: host
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: mysql-configmap
                key: name
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: mysql-credentials-secret
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-credentials-secret
                key: password
          - name: JAEGER_AGENT_HOST
            value: jaeger-agent
        ports:
        - name: user-svc-port
          containerPort: 8080
        imagePullPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
    name: user-service
spec:
    selector:
        app: user-service
        tier: backend
    type: ClusterIP
    ports:
      - protocol: TCP
        port: 8082
        targetPort: user-svc-port